"""Renders a snapshot dict (analysis/snapshot.py) into one self-contained HTML
file — inline CSS/JS, the data embedded as a JSON blob, no external requests.
Whoever opens it needs no backend, no Docker, no LLM key: just a browser.
"""

import json

_TEMPLATE = r"""<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>__TITLE__</title>
<meta name="viewport" content="width=device-width, initial-scale=1">
<style>
  :root { --bg:#0f0f10; --surface:#17181a; --surface2:#1e1f22; --border:#2a2b2e; --text:#e8e8ea;
          --text2:#a6a7ab; --text3:#77787d; --accent:#6ea8fe; --mono: ui-monospace, "SF Mono", Menlo, monospace; }
  * { box-sizing: border-box; }
  body { margin:0; background:var(--bg); color:var(--text); font: 14px/1.55 -apple-system, Segoe UI, sans-serif; }
  header { padding:22px 28px; border-bottom:1px solid var(--border); display:flex; align-items:center; gap:16px; flex-wrap:wrap; }
  header h1 { font-size:18px; margin:0; }
  header .sub { color:var(--text3); font-size:12.5px; }
  .counts { margin-left:auto; display:flex; gap:18px; }
  .counts b { display:block; font-size:16px; font-variant-numeric:tabular-nums; }
  .counts span { font-size:10.5px; color:var(--text3); text-transform:uppercase; letter-spacing:.04em; }
  nav { display:flex; gap:4px; padding:10px 28px; border-bottom:1px solid var(--border); overflow-x:auto; }
  nav button { background:none; border:1px solid transparent; color:var(--text2); padding:7px 13px;
               border-radius:7px; cursor:pointer; font-size:12.5px; white-space:nowrap; }
  nav button.on { background:var(--surface2); color:var(--text); border-color:var(--border); }
  main { padding:22px 28px; max-width:1100px; }
  .card { background:var(--surface); border:1px solid var(--border); border-radius:12px; padding:18px 20px; margin-bottom:14px; }
  .card h2 { font-size:13px; text-transform:uppercase; letter-spacing:.04em; color:var(--text3); margin:0 0 10px; }
  .row { display:flex; justify-content:space-between; gap:12px; padding:8px 0; border-top:1px solid var(--border); font-size:13px; }
  .row:first-child { border-top:none; }
  .mono { font-family:var(--mono); font-size:12.5px; }
  .muted { color:var(--text3); }
  .chip { display:inline-block; background:var(--surface2); border:1px solid var(--border); border-radius:999px;
          padding:2px 10px; font-size:11px; margin:2px 4px 2px 0; color:var(--text2); }
  .why { color:var(--text2); font-size:12.5px; margin-top:3px; }
  #graph { width:100%; height:520px; background:var(--surface); border:1px solid var(--border); border-radius:12px; cursor:grab; }
  .empty { color:var(--text3); font-size:12.5px; padding:10px 0; }
  .codeblk { margin:8px 0 14px; }
  .codebar { padding:6px 11px; background:var(--surface2); border:1px solid var(--border); border-bottom:none; border-radius:8px 8px 0 0; font-size:12px; }
  .codeblk pre { margin:0; background:var(--surface); border:1px solid var(--border); border-radius:0 0 8px 8px; padding:12px 14px; overflow-x:auto; font-size:12px; line-height:1.55; }
  code { font-family:var(--mono); font-size:12px; background:var(--surface2); padding:1px 5px; border-radius:4px; }
  footer { padding:16px 28px; color:var(--text3); font-size:11.5px; }
</style>
</head>
<body>
<header>
  <h1>__TITLE__</h1>
  <div class="sub">Shared snapshot &middot; generated __GENERATED_AT__ &middot; static, no backend required</div>
  <div class="counts">
    <div><b id="c-files"></b><span>Files</span></div>
    <div><b id="c-symbols"></b><span>Symbols</span></div>
    <div><b id="c-edges"></b><span>Deps</span></div>
  </div>
</header>
<nav id="nav"></nav>
<main id="main"></main>
<footer>Generated by CoderLens. This file is self-contained — the data above will not change even if the source repository does.</footer>

<script id="snapshot-data" type="application/json">__DATA_JSON__</script>
<script>
const D = JSON.parse(document.getElementById('snapshot-data').textContent);
document.getElementById('c-files').textContent = D.counts.files.toLocaleString();
document.getElementById('c-symbols').textContent = D.counts.symbols.toLocaleString();
document.getElementById('c-edges').textContent = D.counts.edges.toLocaleString();

const TABS = [
  ['overview', 'Overview'], ['wiki', 'Start here'], ['entrypoints', 'Entrypoints'],
  ['deadcode', 'Dead code'], ['communities', 'Communities'], ['coupling', 'Coupling'], ['graph', 'Graph'],
];
const nav = document.getElementById('nav'), main = document.getElementById('main');
const esc = (s) => (s ?? '').toString().replace(/[&<>]/g, (c) => ({'&':'&amp;','<':'&lt;','>':'&gt;'}[c]));
const md = (s) => esc(s).replace(/\*\*(.+?)\*\*/g, '<b>$1</b>');

function renderOverview() {
  const a = D.architecture;
  return `<div class="card"><h2>Architecture</h2><p>${esc(a.summary)}</p>
    <p class="muted">Style: ${esc(a.style)}</p></div>
    <div class="card"><h2>Submodules</h2>
      ${a.layers.map(l => `<div class="row"><span class="mono">${esc(l.submodule)}</span><span class="muted">${esc(l.responsibility)}</span></div>`).join('') || '<div class="empty">None found.</div>'}
    </div>`;
}
function mdText(s) {
  return esc(s).replace(/\*\*(.+?)\*\*/g, '<b>$1</b>').replace(/`([^`]+)`/g, '<code>$1</code>');
}
function renderBlock(b) {
  if (b.kind === 'md') return b.text.split(/\n\s*\n/).map(p => `<p>${mdText(p.trim())}</p>`).join('');
  if (b.kind === 'p') return `<p>${mdText(b.text)}</p>`;
  if (b.kind === 'h2') return `<h3 style="margin:18px 0 8px">${esc(b.text)}</h3>`;
  if (b.kind === 'list') return `<ul>${b.items.map(i => `<li>${mdText(i)}</li>`).join('')}</ul>`;
  if (b.kind === 'table') return `<table style="width:100%;border-collapse:collapse;font-size:12.5px">
    <thead><tr>${b.columns.map(c => `<th style="text-align:left;padding:5px 10px 5px 0;color:var(--text3);border-bottom:1px solid var(--border)">${esc(c)}</th>`).join('')}</tr></thead>
    <tbody>${b.rows.map(r => `<tr>${r.map(cell => `<td style="padding:8px 10px 8px 0;border-bottom:1px solid var(--border)">${mdText(cell)}</td>`).join('')}</tr>`).join('')}</tbody>
  </table>`;
  if (b.kind === 'chips') return `<div>${b.chips.map(c => `<span class="chip mono">${esc(c.text)}</span>`).join('')}</div>`;
  if (b.kind === 'code') return `<div class="codeblk"><div class="codebar mono">${esc(b.title)} <span class="muted">${esc(b.path)}:${b.line}</span></div><pre class="mono">${esc(b.code)}</pre></div>`;
  if (b.kind === 'diagram') {
    // No renderer bundled in this static file (it must make no external
    // requests) — extract the arrow list from the Mermaid source so the real
    // structure (who calls what) stays readable without a renderer.
    const labels = {};
    (b.mermaid.match(/(\w+)\["([^"]*)"\]/g) || []).forEach(tok => {
      const m = tok.match(/(\w+)\["([^"]*)"\]/); if (m) labels[m[1]] = m[2];
    });
    const rows = b.mermaid.split('\n')
      .map(l => l.trim().match(/^(\w+)\s*-->\s*(\w+)$/)).filter(Boolean)
      .map(m => `<div class="row"><span class="mono">${esc(labels[m[1]] || m[1])}</span><span class="muted">&rarr; ${esc(labels[m[2]] || m[2])}</span></div>`).join('');
    return `<div class="card"><h2>${esc(b.title)}</h2>${rows || '<div class="empty">Open the live app to view this diagram.</div>'}</div>`;
  }
  return '';
}
function renderWiki() {
  const w = D.wiki;
  return w.sections.map(sec => `<details class="card" open>
      <summary style="cursor:pointer;font-weight:600">${esc(sec.title)} <span class="muted" style="font-weight:400">— ${esc(sec.subtitle)}</span></summary>
      <div style="margin-top:10px">${sec.blocks.map(renderBlock).join('')}</div>
    </details>`).join('');
}
function renderEntrypoints() {
  if (!D.entrypoints.length) return '<div class="empty">None found.</div>';
  return '<div class="card">' + D.entrypoints.map(e =>
    `<div class="row"><span><span class="chip">${esc(e.kind)}</span> ${esc(e.label)}</span>
     <span class="mono muted">${esc(e.path)}:${e.line}</span></div>`).join('') + '</div>';
}
function renderDeadCode() {
  const d = D.dead_code;
  if (!d.candidates.length) return '<div class="empty">None found.</div>';
  return `<div class="card"><h2>${d.counts.total} candidates &middot; ${d.counts.private} private &middot; ${d.counts.public} public</h2>` +
    d.candidates.map(c => `<div class="row"><span class="mono">${esc(c.qualified_name)}</span>
      <span class="muted">${esc(c.path)}:${c.line}</span></div>`).join('') + '</div>';
}
function renderCommunities() {
  if (!D.communities.clusters.length) return '<div class="empty">None found.</div>';
  return D.communities.clusters.map(c => `<div class="card"><h2>${esc(c.label)} &middot; ${c.size} symbols</h2>
    <div class="muted" style="font-size:12px;margin-bottom:6px">Mostly in ${esc(c.primary_dir)}</div>
    ${c.members.slice(0,10).map(m => `<div class="row"><span class="mono">${esc(m.qualified_name)}</span><span class="muted">${esc(m.path)}:${m.line}</span></div>`).join('')}
    </div>`).join('');
}
function renderCoupling() {
  if (!D.coupling.pairs.length) return '<div class="empty">None found.</div>';
  return '<div class="card">' + D.coupling.pairs.map(p =>
    `<div class="row"><span class="mono">${esc(p.a)} &times; ${esc(p.b)}</span><span class="muted">${p.co_changes} commits together</span></div>`).join('') + '</div>';
}

function renderGraph() {
  return '<canvas id="graph"></canvas><p class="muted" style="margin-top:8px;font-size:11.5px">Drag to pan, scroll to zoom, click a node to highlight its direct dependencies. Box size = how connected a file is.</p>';
}

const RENDER = { overview: renderOverview, wiki: renderWiki, entrypoints: renderEntrypoints,
  deadcode: renderDeadCode, communities: renderCommunities, coupling: renderCoupling, graph: renderGraph };

let active = 'overview';
function show(tab) {
  active = tab;
  nav.querySelectorAll('button').forEach(b => b.classList.toggle('on', b.dataset.tab === tab));
  main.innerHTML = RENDER[tab]();
  if (tab === 'graph') setTimeout(initGraph, 0);
}
TABS.forEach(([key, label]) => {
  const b = document.createElement('button');
  b.textContent = label; b.dataset.tab = key; b.onclick = () => show(key);
  nav.appendChild(b);
});
show('overview');

// Minimal force-directed layout — same idea as the live app's Explorer, just
// self-contained vanilla JS since this file has no bundler or React.
function initGraph() {
  const cv = document.getElementById('graph');
  if (!cv) return;
  const ctx = cv.getContext('2d');
  const nodes = D.graph.nodes.map((n, i) => ({ ...n, x: Math.cos(i) * 200, y: Math.sin(i * 1.7) * 200, vx: 0, vy: 0 }));
  const byId = new Map(nodes.map(n => [n.id, n]));
  const links = D.graph.links.map(l => ({ s: byId.get(l.source), t: byId.get(l.target), w: l.weight || 1 })).filter(l => l.s && l.t);
  let W = 0, H = 0, scale = 1, px = 0, py = 0, sel = null;
  function size() { const r = cv.parentElement.getBoundingClientRect(); W = cv.width = r.width; H = cv.height = 520; }
  function fit() {
    let a=1e9,b=1e9,c=-1e9,d=-1e9;
    nodes.forEach(n => { a=Math.min(a,n.x); b=Math.min(b,n.y); c=Math.max(c,n.x); d=Math.max(d,n.y); });
    const pad=80, w=(c-a)||1, h=(d-b)||1;
    scale = Math.min((W-pad)/w, (H-pad)/h, 2.2);
    px = W/2 - (a+c)/2*scale; py = H/2 - (b+d)/2*scale;
  }
  function tick() {
    for (const n of nodes) { n.vx += -n.x*0.01; n.vy += -n.y*0.01; }
    for (let i=0;i<nodes.length;i++) for (let j=i+1;j<nodes.length;j++) {
      const p=nodes[i], q=nodes[j]; let dx=p.x-q.x, dy=p.y-q.y, d2=dx*dx+dy*dy+0.01;
      const f=3800/d2, dd=Math.sqrt(d2); dx/=dd; dy/=dd;
      p.vx+=dx*f; p.vy+=dy*f; q.vx-=dx*f; q.vy-=dy*f;
    }
    for (const l of links) {
      let dx=l.t.x-l.s.x, dy=l.t.y-l.s.y, d=Math.sqrt(dx*dx+dy*dy)+0.01;
      const f=(d-70)*0.01; dx/=d; dy/=d;
      l.s.vx+=dx*f; l.s.vy+=dy*f; l.t.vx-=dx*f; l.t.vy-=dy*f;
    }
    for (const n of nodes) { n.vx*=0.85; n.vy*=0.85; n.x+=n.vx; n.y+=n.vy; }
  }
  const toScreen = (n) => ({ x: n.x*scale+px, y: n.y*scale+py });
  function draw() {
    ctx.clearRect(0,0,W,H);
    const nb = sel ? new Set([sel.id, ...links.filter(l=>l.s.id===sel.id||l.t.id===sel.id).map(l=>l.s.id===sel.id?l.t.id:l.s.id)]) : null;
    for (const l of links) {
      const a = toScreen(l.s), b = toScreen(l.t);
      const on = sel && (l.s.id===sel.id || l.t.id===sel.id);
      ctx.globalAlpha = sel ? (on ? 1 : 0.08) : 0.5;
      ctx.strokeStyle = on ? '#6ea8fe' : '#3a3b3e'; ctx.lineWidth = on ? 1.8 : 1;
      ctx.beginPath(); ctx.moveTo(a.x,a.y); ctx.lineTo(b.x,b.y); ctx.stroke();
    }
    ctx.globalAlpha = 1;
    for (const n of nodes) {
      const p = toScreen(n), r = (3 + Math.sqrt(n.degree||1)*1.6) * Math.max(0.7, Math.min(1.3, scale));
      ctx.globalAlpha = nb && !nb.has(n.id) ? 0.25 : 1;
      ctx.beginPath(); ctx.arc(p.x,p.y,r,0,Math.PI*2); ctx.fillStyle = '#6ea8fe'; ctx.fill();
      if (n.id === sel?.id || r > 5) {
        ctx.fillStyle = '#e8e8ea'; ctx.font = '10px monospace'; ctx.textAlign='center';
        ctx.fillText((n.label||'').slice(0,26), p.x, p.y + r + 11);
      }
    }
  }
  function loop() { tick(); draw(); requestAnimationFrame(loop); }
  let panning=false, last={x:0,y:0}, moved=false;
  cv.addEventListener('mousedown', (e) => { panning=true; moved=false; last={x:e.offsetX,y:e.offsetY}; });
  window.addEventListener('mousemove', (e) => {
    if (!panning) return; moved=true;
    const r=cv.getBoundingClientRect(), sx=e.clientX-r.left, sy=e.clientY-r.top;
    px += sx-last.x; py += sy-last.y; last={x:sx,y:sy};
  });
  window.addEventListener('mouseup', (e) => {
    panning=false;
    if (moved) return;
    const r=cv.getBoundingClientRect(), sx=e.clientX-r.left, sy=e.clientY-r.top;
    let best=null, bd=1e9;
    for (const n of nodes) { const p=toScreen(n); const d=(p.x-sx)**2+(p.y-sy)**2; if (d<400 && d<bd) { bd=d; best=n; } }
    sel = best;
  });
  cv.addEventListener('wheel', (e) => {
    e.preventDefault();
    const f = e.deltaY<0 ? 1.1 : 1/1.1;
    const r=cv.getBoundingClientRect(), sx=e.clientX-r.left, sy=e.clientY-r.top;
    const wx=(sx-px)/scale, wy=(sy-py)/scale;
    scale = Math.max(0.2, Math.min(4, scale*f));
    px = sx - wx*scale; py = sy - wy*scale;
  }, { passive:false });
  size();
  for (let i=0;i<200;i++) tick();
  fit();
  loop();
  window.addEventListener('resize', () => { size(); });
}
</script>
</body>
</html>
"""


def render_snapshot_html(snapshot: dict, generated_at: str) -> str:
    title = f"{snapshot['repo']} — shared snapshot"
    data_json = json.dumps(snapshot).replace("</script>", "<\\/script>")
    return (_TEMPLATE
            .replace("__TITLE__", title)
            .replace("__GENERATED_AT__", generated_at)
            .replace("__DATA_JSON__", data_json))
